#!/usr/bin/env bash
# Displays the username, user id, and home directory path for each user in /etc/passwd

while IFS=: read -r username _ userid _ _ _ homedir _
do
    echo "$username:$userid:$homedir"
done < /etc/passwd
