#!/usr/bin/env bash
# Displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi.

count=1

while [ $count -le 10 ]
do
    echo "Best School"
    if [ $count -eq 9 ]; then
        echo "Hi"
    fi
    count=$((count + 1))
done
