#!/bin/bash

# 11-manage_my_process script

PID_FILE="/var/run/my_process.pid"
LOG_FILE="/tmp/my_process"
PROCESS_NAME="manage_my_process"

start() {
  if [ -f "$PID_FILE" ]; then
    echo "$PROCESS_NAME is already running."
  else
    # Start the process in the background
    ./$PROCESS_NAME &
    # Save the PID to the PID file
    echo $! > "$PID_FILE"
    echo "$PROCESS_NAME started"
  fi
}

stop() {
  if [ -f "$PID_FILE" ]; then
    # Kill the process using the PID from the PID file
    kill $(cat "$PID_FILE")
    # Remove the PID file
    rm "$PID_FILE"
    echo "$PROCESS_NAME stopped"
  else
    echo "$PROCESS_NAME is not running."
  fi
}

restart() {
  stop
  start
  echo "$PROCESS_NAME restarted"
}

manage_my_process() {
  while true; do
    echo "I am alive!" >> "$LOG_FILE"
    sleep 2
  done
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    ;;
esac
