#!/usr/bin/env bash
# This script manages itself to write "I am alive!" to /tmp/my_process

manage_my_process() {
    while true; do
        echo "I am alive!" >> /tmp/my_process
        sleep 2
    done
}

start_process() {
    if [ -f /var/run/my_process.pid ]; then
        echo "manage_my_process is already running"
        exit 1
    fi
    manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
}

stop_process() {
    if [ -f /var/run/my_process.pid ]; then
        PID=$(cat /var/run/my_process.pid)
        kill "$PID"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac

